# -*- coding: utf-8 -*-
"""noise_filtering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RhZcO8al6_4IFmbefBba_jIM5CSKjXAH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt, iirnotch

df = pd.read_csv("eeg_numeric_3.csv")
df.head()

"""# Noise detection using slinding window"""

channels = ['TP9', 'AF7', 'AF8', 'TP10']
eeg = df[channels].values
timestamps = df['lsl_timestamp'].values

fs = 256

print("EEG data loaded:", eeg.shape)

win_sec = 1  # 1-second windows
win_samples = fs * win_sec

"""1. Flatline and spike detection"""

def detect_spikes_flatlines(signal, spike_thresh=100, flatline_thresh=1e-6, window_size_sec=0.5, fs=256):
    """
    Detects spikes and flatlines in an EEG channel.

    Parameters:
        signal (np.array): 1D EEG signal
        spike_thresh (float): amplitude jump threshold for spikes (µV)
        flatline_thresh (float): minimum std threshold for flatlines (µV)
        window_size_sec (float): size of sliding window in seconds
        fs (int): sampling rate in Hz

    Returns:
        bad_indices (np.array): indices of signal marked as bad
        spike_indices (np.array): indices of spikes
        flatline_indices (np.array): indices of flatlines
    """
    N = len(signal)
    window_size = int(fs * window_size_sec)
    bad_indices = []
    spike_indices = []
    flatline_indices = []

    for start in range(0, N - window_size, window_size):
        window = signal[start:start + window_size]
        # Spike detection: large jumps
        diff_window = np.abs(np.diff(window))
        spikes = np.where(diff_window > spike_thresh)[0] + start
        spike_indices.extend(spikes)

        # Flatline detection: low std
        if np.std(window) < flatline_thresh:
            flatline_indices.extend(range(start, start + window_size))

    # Combine all bad indices
    bad_indices = np.unique(np.concatenate([spike_indices, flatline_indices]))

    return np.array(bad_indices), np.array(spike_indices), np.array(flatline_indices)

tp9_signal = eeg[:,0]
bad_idx, spike_idx, flatline_idx = detect_spikes_flatlines(tp9_signal)

print("Total bad points:", len(bad_idx))
print("Spike points:", len(spike_idx))
print("Flatline points:", len(flatline_idx))

import pandas as pd
import numpy as np

def detect_flat_and_spikes(df, channels, window_size=256, flat_var_thresh=1e-6, spike_std_thresh=5):
    """
    Detect flat lines and spikes in EEG data from Muse headband.

    Parameters:
    - df: pandas DataFrame with 'timestamp' + EEG channels
    - channels: list of EEG channels ['TP9','AF7','AF8','TP10']
    - window_size: number of samples to compute variance for flat detection
    - flat_var_thresh: variance threshold to consider a flat line
    - spike_std_thresh: number of standard deviations to consider a spike

    Returns:
    - flat_dict: dictionary with channel -> list of flat line indices
    - spike_dict: dictionary with channel -> list of spike indices
    """
    flat_dict = {}
    spike_dict = {}

    for ch in channels:
        signal = df[ch].values

        # --- Flat line detection ---
        flat_indices = []
        for i in range(len(signal) - window_size):
            window = signal[i:i+window_size]
            if np.var(window) < flat_var_thresh:
                flat_indices.append(i)
        flat_dict[ch] = flat_indices

        # --- Spike detection ---
        mean = np.mean(signal)
        std = np.std(signal)
        spike_indices = np.where(np.abs(signal - mean) > spike_std_thresh * std)[0]
        spike_dict[ch] = spike_indices

    return flat_dict, spike_dict


flats, spikes = detect_flat_and_spikes(df, ['TP9','AF7','AF8','TP10'])
print("Flat line segments:", flats)
# print("Spike indices:", spikes)

import matplotlib.pyplot as plt

def plot_eeg_per_channel(df, channels, flat_dict, spike_dict):
    """
    Plot EEG signals with spikes and flat lines highlighted for each channel in separate subplots.

    Parameters:
    - df: DataFrame with 'lsl_timestamp' + EEG channels
    - channels: list of EEG channels
    - flat_dict: dict from detect_flat_and_spikes
    - spike_dict: dict from detect_flat_and_spikes
    """
    n_channels = len(channels)
    fig, axes = plt.subplots(n_channels, 1, figsize=(16, 3*n_channels), sharex=True)

    if n_channels == 1:
        axes = [axes]  # ensure axes is iterable

    for i, ch in enumerate(channels):
        ax = axes[i]
        signal = df[ch].values
        t = df['lsl_timestamp'].values

        ax.plot(t, signal, color='blue', label='EEG signal')

        # Highlight flat lines (red shaded regions)
        for idx in flat_dict[ch]:
            start = t[idx]
            end = t[min(idx+1, len(t)-1)]
            ax.axvspan(start, end, color='red', alpha=0.3)

        # Highlight spikes (green dots)
        spike_times = t[spike_dict[ch]]
        spike_vals = signal[spike_dict[ch]]
        ax.scatter(spike_times, spike_vals, color='green', s=10, label='Spikes')

        ax.set_ylabel(f'{ch} (μV)')
        ax.legend(loc='upper right')
        ax.grid(True)

    axes[-1].set_xlabel('Time (s)')
    plt.suptitle('EEG Channels with Spikes (green) and Flat Lines (red)', fontsize=16)
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.show()

# --- Example Usage ---
flats, spikes = detect_flat_and_spikes(df, channels, window_size=256, flat_var_thresh=1e-6, spike_std_factor=4)
plot_eeg_per_channel(df, channels, flats, spikes)

"""3. High variance"""

def detect_high_frequency_channels(eeg_data, fs=256, hf_freq=30, hf_ratio=0.3, window_sec=1.0, channels=None):
    """
    Detects segments where high-frequency power dominates for each EEG channel.

    Parameters:
        eeg_data (np.array): [nsamples x n_channels] EEG signals
        fs (int): sampling rate in Hz
        hf_freq (float): frequency threshold to consider high-frequency (Hz)
        hf_ratio (float): fraction of power above hf_freq to mark as high-frequency
        window_sec (float): window size for FFT analysis (seconds)
        channels (list): list of channel names (optional)

    Returns:
        hf_dict (dict): {channel_name: array of indices of high-frequency segments}
    """
    if channels is None:
        channels = [f'ch{i}' for i in range(eeg_data.shape[1])]

    n_channels = eeg_data.shape[1]
    hf_dict = {}

    for i in range(n_channels):
        sig = eeg_data[:, i]
        window_size = int(fs * window_sec)
        hf_indices = []

        for start in range(0, len(sig) - window_size, window_size):
            window = sig[start:start+window_size]
            fft_vals = np.abs(np.fft.rfft(window))
            freqs = np.fft.rfftfreq(len(window), d=1/fs)

            total_power = np.sum(fft_vals)
            hf_power = np.sum(fft_vals[freqs > hf_freq])
            if total_power > 0 and (hf_power / total_power) > hf_ratio:
                hf_indices.extend(range(start, start + window_size))

        hf_dict[channels[i]] = np.array(hf_indices)

    return hf_dict

hf_result = detect_high_frequency_channels(eeg, fs=256, hf_freq=30, hf_ratio=0.3, window_sec=0.5, channels=channels)

for ch in channels:
    print(f"{ch}: High-frequency points = {len(hf_result[ch])}")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# --- 1. Flat line & spike detection ---
def detect_flat_and_spikes(df, channels, window_size=256, flat_var_thresh=1e-6, spike_std_factor=4):
    flat_dict = {}
    spike_dict = {}

    for ch in channels:
        signal = df[ch].values

        # --- Flat line detection ---
        flat_indices = []
        for i in range(len(signal) - window_size):
            window = signal[i:i+window_size]
            if np.var(window) < flat_var_thresh:
                flat_indices.append(i)
        flat_dict[ch] = flat_indices

        # --- Spike detection ---
        mean = np.mean(signal)
        std = np.std(signal)
        spike_indices = np.where(np.abs(signal - mean) > spike_std_factor * std)[0]
        spike_dict[ch] = spike_indices

    return flat_dict, spike_dict

# --- 2. High-frequency detection ---
def detect_high_frequency_channels(eeg_data, fs=256, hf_freq=30, hf_ratio=0.3, window_sec=0.5, channels=None):
    if channels is None:
        channels = [f'ch{i}' for i in range(eeg_data.shape[1])]

    n_channels = eeg_data.shape[1]
    hf_dict = {}

    for i in range(n_channels):
        sig = eeg_data[:, i]
        window_size = int(fs * window_sec)
        hf_indices = []

        for start in range(0, len(sig) - window_size, window_size):
            window = sig[start:start+window_size]
            fft_vals = np.abs(np.fft.rfft(window))
            freqs = np.fft.rfftfreq(len(window), d=1/fs)

            total_power = np.sum(fft_vals)
            hf_power = np.sum(fft_vals[freqs > hf_freq])
            if total_power > 0 and (hf_power / total_power) > hf_ratio:
                hf_indices.extend(range(start, start + window_size))

        hf_dict[channels[i]] = np.array(hf_indices)

    return hf_dict

# --- 3. Plotting function ---
def plot_eeg_with_artifacts(df, channels, flat_dict, spike_dict, hf_dict):
    n_channels = len(channels)
    fig, axes = plt.subplots(n_channels, 1, figsize=(16, 3*n_channels), sharex=True)

    if n_channels == 1:
        axes = [axes]

    for i, ch in enumerate(channels):
        ax = axes[i]
        signal = df[ch].values
        t = df['lsl_timestamp'].values

        ax.plot(t, signal, color='blue', label='EEG signal')

        # Flat lines (red)
        flat_idx = flat_dict[ch]
        if len(flat_idx) > 0:
            ax.scatter(t[flat_idx], signal[flat_idx], color='red', s=10, label='Flat line')

        # Spikes (green)
        spike_idx = spike_dict[ch]
        if len(spike_idx) > 0:
            ax.scatter(t[spike_idx], signal[spike_idx], color='green', s=10, label='Spikes')

        # High-frequency (orange)
        hf_idx = hf_dict[ch]
        if len(hf_idx) > 0:
            ax.scatter(t[hf_idx], signal[hf_idx], color='orange', s=5, label='High-Freq')

        ax.set_ylabel(f'{ch} (μV)')
        ax.legend(loc='upper right')
        ax.grid(True)

    axes[-1].set_xlabel('Time (s)')
    plt.suptitle('EEG Channels with Flat Lines (red), Spikes (green), High-Frequency (orange)', fontsize=16)
    plt.tight_layout(rect=[0,0,1,0.95])
    plt.show()

# --- 4. Example usage ---
channels = ['TP9','AF7','AF8','TP10']

# Detect flat lines and spikes
flats, spikes = detect_flat_and_spikes(df, channels, window_size=256, flat_var_thresh=1e-6, spike_std_factor=4)

# Convert df to numpy array for high-frequency detection
eeg_array = df[channels].values
hf_result = detect_high_frequency_channels(eeg_array, fs=256, hf_freq=50, hf_ratio=0.3, window_sec=0.5, channels=channels)

# Plot combined artifacts
plot_eeg_with_artifacts(df, channels, flats, spikes, hf_result)

def plot_high_frequency_segments(df, channels, hf_dict):
    """
    Plot EEG channels with high-frequency segments highlighted.
    """
    n_channels = len(channels)
    fig, axes = plt.subplots(n_channels, 1, figsize=(16, 3*n_channels), sharex=True)

    if n_channels == 1:
        axes = [axes]

    for i, ch in enumerate(channels):
        ax = axes[i]
        signal = df[ch].values
        t = df['lsl_timestamp'].values

        ax.plot(t, signal, color='blue', label='EEG signal')

        # Highlight high-frequency segments
        hf_idx = hf_dict[ch]
        if len(hf_idx) > 0:
            ax.scatter(t[hf_idx], signal[hf_idx], color='orange', s=10, label='High-Frequency')

        ax.set_ylabel(f'{ch} (μV)')
        ax.legend(loc='upper right')
        ax.grid(True)

    axes[-1].set_xlabel('Time (s)')
    plt.suptitle('EEG Channels with High-Frequency Segments (orange)', fontsize=16)
    plt.tight_layout(rect=[0,0,1,0.96])
    plt.show()

# Example usage:
plot_high_frequency_segments(df, channels, hf_result)

"""4. High-frequency noise"""

def detect_high_variance_channels(eeg_data, fs=256, var_threshold=100, window_sec=0.5, channels=None):
    """
    Detects high-variance segments in each EEG channel.

    Parameters:
        eeg_data (np.array): [nsamples x n_channels] EEG signals
        fs (int): sampling rate in Hz
        var_threshold (float): variance threshold for high-variance
        window_sec (float): window size for checking variance (seconds)
        channels (list): list of channel names (optional)

    Returns:
        hv_dict (dict): {channel_name: array of indices of high-variance segments}
    """
    if channels is None:
        channels = [f'ch{i}' for i in range(eeg_data.shape[1])]

    n_channels = eeg_data.shape[1]
    hv_dict = {}

    for i in range(n_channels):
        sig = eeg_data[:, i]
        window_size = int(fs * window_sec)
        hv_indices = []

        for start in range(0, len(sig) - window_size, window_size):
            window = sig[start:start+window_size]
            if np.var(window) > var_threshold:
                hv_indices.extend(range(start, start + window_size))

        hv_dict[channels[i]] = np.array(hv_indices)

    return hv_dict

channels = ['TP9', 'AF7', 'AF8', 'TP10']
hv_result = detect_high_variance_channels(eeg, fs=256, var_threshold=100, window_sec=0.1, channels=channels)

for ch in channels:
    print(f"{ch}: High-variance points = {len(hv_result[ch])}")

"""# Filtering Noise

Band-pass and Notch filtering
"""

def bandpass_filter(signal, lowcut=1, highcut=45, fs=256, order=4):
  nyq = 0.5 * fs
  b, a = butter(order, [lowcut/nyq, highcut/nyq], btype='band')
  return filtfilt(b, a, signal)

def notch_filter(signal, freq=50, fs=256, Q=30):
  b, a = iirnotch(freq/(fs/2), Q)
  return filtfilt(b, a, signal)

filtered_eeg = np.zeros_like(eeg)

for i, ch in enumerate(channels):
  sig = eeg[:, i]
  sig_f = bandpass_filter(sig)
  sig_f = notch_filter(sig_f)
  filtered_eeg[:, i] = sig_f

def high_freq_ratio(signal, fs):
    f, pxx = welch(signal, fs=fs, nperseg=fs)
    hf_power = pxx[(f >= 30) & (f <= 80)].sum()
    return hf_power / pxx.sum()

# -------------------------
# Compute variance and high-frequency power fraction per channel
# -------------------------
def high_freq_fraction(signal, fs=256, hf_freq=30):
    """
    Compute fraction of signal power above hf_freq.
    """
    fft_vals = np.abs(np.fft.rfft(signal))
    freqs = np.fft.rfftfreq(len(signal), d=1/fs)
    total_power = np.sum(fft_vals)
    hf_power = np.sum(fft_vals[freqs > hf_freq])
    return hf_power / total_power if total_power > 0 else 0

print(f"{'Channel':<5} | {'Var Before':>10} | {'Var After':>10} | {'HF frac Before':>15} | {'HF frac After':>15}")
print("-"*65)

for i, ch in enumerate(channels):
    sig_raw = eeg[:, i]
    sig_filt = filtered_eeg[:, i]

    var_before = np.var(sig_raw)
    var_after = np.var(sig_filt)

    hf_before = high_freq_fraction(sig_raw, fs=fs, hf_freq=30)
    hf_after = high_freq_fraction(sig_filt, fs=fs, hf_freq=30)

    print(f"{ch:<5} | {var_before:10.2f} | {var_after:10.2f} | {hf_before:15.3f} | {hf_after:15.3f}")

# -------------------------
# Block 2: Visualize Raw + Filtered EEG with Noise Highlights
# -------------------------
for i, ch in enumerate(channels):
    plt.figure(figsize=(15,3))
    # Raw EEG
    plt.plot(timestamps, eeg[:,i], alpha=0.5, label='Raw EEG')
    # Filtered EEG
    plt.plot(timestamps, filtered_eeg[:,i], color='red', label='Filtered EEG')
    # High-variance noise
    plt.scatter(timestamps[hv_result[ch]], eeg[hv_result[ch],i], color='orange', s=20, label='High-variance')
    # High-frequency noise
    plt.scatter(timestamps[hf_result[ch]], eeg[hf_result[ch],i], color='purple', s=20, label='High-frequency')

    plt.title(f"{ch}: Noise Detection + Filtered EEG")
    plt.xlabel("Time (s)")
    plt.ylabel("µV")
    plt.legend()
    plt.tight_layout()
    plt.show()

# -------------------------
# Generate noise signal + filtered signal per channel
# -------------------------
for i, ch in enumerate(channels):
    # Extract high-variance + high-frequency indices as noise
    noise_idx = np.unique(np.concatenate([hv_result[ch], hf_result[ch]]))
    noise_signal = np.zeros_like(filtered_eeg[:, i])
    noise_signal[noise_idx] = filtered_eeg[noise_idx, i]  # keep only noisy parts

    # Filtered signal (already computed)
    clean_signal = filtered_eeg[:, i]

    # Plot
    plt.figure(figsize=(15,4))
    plt.plot(timestamps, clean_signal, color='red', label='Filtered EEG')
    plt.plot(timestamps, noise_signal, color='blue', label='Noise Signal')
    plt.title(f"{ch}: Noise vs Filtered EEG")
    plt.xlabel("Time (s)")
    plt.ylabel("µV")
    plt.legend()
    plt.tight_layout()
    plt.show()

plt.figure(figsize=(15,3))
plt.plot(timestamps, noise_signal, color='blue', alpha=0.5, label="Noise signal")
plt.plot(timestamps, filtered_eeg[:,0], color='red', label="Filtered EEG")
plt.xlabel("Time (s)")
plt.ylabel("µV")
plt.title("Time-domain: Noise vs Filtered EEG (TP9)")
plt.legend()
plt.show()

for i, ch in enumerate(channels):
    # Create a boolean mask for noise segments
    noise_idx = np.unique(np.concatenate([hv_result[ch], hf_result[ch]]))
    noise_mask = np.zeros(len(filtered_eeg[:,i]))
    noise_mask[noise_idx] = 1  # just mark presence of noise

    plt.figure(figsize=(15,3))

    # Plot filtered EEG
    plt.plot(timestamps, filtered_eeg[:,i], color='red', label='Filtered EEG')

    # Shade noise regions
    plt.fill_between(timestamps,
                     filtered_eeg[:,i].min(),
                     filtered_eeg[:,i].max(),
                     where=noise_mask>0,
                     color='blue', alpha=0.3, label='Noise regions')

    plt.title(f"{ch}: Filtered EEG with Noise Highlighted")
    plt.xlabel("Time (s)")
    plt.ylabel("µV")
    plt.legend()
    plt.tight_layout()
    plt.show()

"""# FFT"""

# -------------------------
# Block 1: Normalize EEG signals to [-1, 1] (optional)
# -------------------------
import numpy as np

def normalize_signals(matrix):
    """
    Scale each signal in matrix to [-1, 1].
    """
    matrix_norm = -1 + 2 * (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
    return matrix_norm

# Example usage
matrix = filtered_eeg  # filtered EEG from previous blocks
matrix_norm = normalize_signals(matrix)

# -------------------------
# Block 2: Compute FFT
# -------------------------
from scipy.fft import fft

def compute_fft(matrix, period=1.0):
    """
    Compute absolute FFT of each column in matrix.
    Returns FFT values and corresponding frequencies.
    """
    N = matrix.shape[0]
    T = period / N  # sampling period
    fft_values = np.abs(fft(matrix, axis=0))[0:N//2] * 2 / N
    freqs = np.linspace(0.0, 1.0/(2.0*T), N//2)
    return fft_values, freqs

# Example usage
fft_vals, freqs = compute_fft(matrix_norm, period=1.0)

# -------------------------
# Block 3: Filter DC and mains frequency
# -------------------------
def filter_fft(fft_values, freqs, filter_DC=True, filter_mains=True, mains_f=50):
    """
    Removes DC (0 Hz) and mains frequency (±1 Hz) from FFT values and frequencies.
    """
    if filter_DC:
        fft_values = fft_values[1:]
        freqs = freqs[1:]
    if filter_mains:
        indx = np.where(np.abs(freqs - mains_f) <= 1)
        fft_values = np.delete(fft_values, indx, axis=0)
        freqs = np.delete(freqs, indx)
    return fft_values, freqs

# Example usage
fft_filtered, freqs_filtered = filter_fft(fft_vals, freqs)

# -------------------------
# Block 4: Extract top-N frequency components
# -------------------------
def top_n_frequencies(fft_values, freqs, ntop=10):
    """
    Returns the top-N frequencies (highest FFT magnitude) for each signal.
    """
    # Sort indices for each column
    indx = np.argsort(fft_values, axis=0)[::-1][:ntop]
    top_freqs = freqs[indx].flatten(order='F')
    return top_freqs

# Example usage
top_freqs = top_n_frequencies(fft_filtered, freqs_filtered, ntop=10)
print("Top frequencies per channel:", top_freqs)

def plot_top_n_freqs(top_freqs, ntop=10, channel_name="TP9"):
    plt.figure(figsize=(10,4))
    plt.bar(range(1, ntop+1), top_freqs[:ntop])
    plt.xticks(range(1, ntop+1))
    plt.xlabel("Top N Frequencies")
    plt.ylabel("Frequency (Hz)")
    plt.title(f"Top-{ntop} Frequencies: {channel_name}")
    plt.show()

# Example usage
plot_top_n_freqs(top_freqs, ntop=10, channel_name="TP9")

# -------------------------
# Block 5: Combine all steps to get features
# -------------------------
def feature_fft(matrix, period=1., mains_f=50.,
                filter_mains=True, filter_DC=True,
                normalise_signals=True,
                ntop=10, get_power_spectrum=True):
    if normalise_signals:
        matrix = normalize_signals(matrix)
    fft_vals, freqs = compute_fft(matrix, period)
    fft_vals, freqs = filter_fft(fft_vals, freqs, filter_DC, filter_mains, mains_f)

    # Extract top-N frequencies
    top_freqs = top_n_frequencies(fft_vals, freqs, ntop)
    ret = top_freqs

    # Make feature names
    names = []
    for i in range(fft_vals.shape[1]):
        names.extend(['topFreq_' + str(j) + "_" + str(i) for j in range(1, ntop+1)])

    # Append full power spectrum if requested
    if get_power_spectrum:
        ret = np.hstack([ret, fft_vals.flatten(order='F')])
        for i in range(fft_vals.shape[1]):
            names.extend(['freq_' + "{:03d}".format(int(j)) + "_" + str(i) for j in 10*np.round(freqs, 1)])

    return ret, names

# Example usage
fft_features, fft_names = feature_fft(filtered_eeg, period=1.0, ntop=10)
print("Feature vector length:", len(fft_features))

import matplotlib.pyplot as plt
from scipy.fft import rfft, rfftfreq

def plot_power_spectrum(signal, fs=256, label="Signal"):
    N = len(signal)
    fft_vals = np.abs(rfft(signal)) * 2 / N
    freqs = rfftfreq(N, 1/fs)

    plt.figure(figsize=(12,4))
    plt.plot(freqs, fft_vals, label=label)
    plt.xlim(0, 60)  # focus on EEG frequency range
    plt.xlabel("Frequency (Hz)")
    plt.ylabel("Amplitude")
    plt.title(f"Power Spectrum: {label}")
    plt.legend()
    plt.show()

# Example usage for a single channel
plot_power_spectrum(filtered_eeg[:,0], fs, label="Filtered EEG")
plot_power_spectrum(noise_signal, fs, label="Noise Signal")

# Overlay both signals in one plot
N = len(filtered_eeg[:,0])
fft_clean = np.abs(rfft(filtered_eeg[:,0])) * 2 / N
fft_noise = np.abs(rfft(noise_signal)) * 2 / N
freqs = rfftfreq(N, 1/fs)

plt.figure(figsize=(12,4))
plt.plot(freqs, fft_clean, color='red', label="Filtered EEG")
plt.plot(freqs, fft_noise, color='blue', label="Noise Signal")
plt.xlim(0, 60)
plt.xlabel("Frequency (Hz)")
plt.ylabel("Amplitude")
plt.title("FFT: Filtered vs Noise Signal (Channel TP9)")
plt.legend()
plt.show()

from scipy.fft import rfft, rfftfreq

N = len(filtered_eeg[:,0])
fft_filtered = np.abs(rfft(filtered_eeg[:,0])) * 2 / N
fft_noise = np.abs(rfft(noise_signal)) * 2 / N
freqs = rfftfreq(N, 1/fs)

plt.figure(figsize=(12,4))
plt.plot(freqs, fft_noise, color='blue', alpha=0.5, label="Noise signal")
plt.plot(freqs, fft_filtered, color='red', label="Filtered EEG")
plt.xlim(0, 60)  # focus on EEG range
plt.xlabel("Frequency (Hz)")
plt.ylabel("Amplitude")
plt.title("Frequency-domain: Noise vs Filtered EEG (TP9)")
plt.legend()
plt.show()







print("===== BEFORE FILTERING =====")
hf_before = {}
var_before = {}

for ch in channels:
    hf_before[ch] = high_freq_ratio(df_raw[ch].values, fs)
    var_before[ch] = np.var(df_raw[ch].values)

    print(f"{ch}: HF ratio = {hf_before[ch]:.3f}, Variance = {var_before[ch]:.1f}")

def bandpass_filter(signal, fs, low=0.5, high=35, order=4):
    b, a = butter(order, [low/(fs/2), high/(fs/2)], btype="band")
    return filtfilt(b, a, signal)

for ch in channels:
    df_filt[ch] = bandpass_filter(df_raw[ch].values, fs)

print("\n===== AFTER FILTERING =====")
hf_after = {}
var_after = {}

for ch in channels:
    hf_after[ch] = high_freq_ratio(df_filt[ch].values, fs)
    var_after[ch] = np.var(df_filt[ch].values)

    hf_red = 100 * (hf_before[ch] - hf_after[ch]) / hf_before[ch]
    var_red = 100 * (var_before[ch] - var_after[ch]) / var_before[ch]

    print(
        f"{ch}: HF ratio = {hf_after[ch]:.3f} "
        f"(↓ {hf_red:.1f}%), "
        f"Variance = {var_after[ch]:.1f} "
        f"(↓ {var_red:.1f}%)"
    )

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt, welch

samples = 2000  # ~8 seconds

plt.figure(figsize=(15,4))
plt.plot(df_raw["AF7"][:samples], label="Raw", alpha=0.7)
plt.plot(df_filt["AF7"][:samples], label="Filtered", linewidth=2)
plt.legend()
plt.title("AF7 — Time domain (Raw vs Band-pass Filtered)")
plt.xlabel("Samples")
plt.ylabel("µV")
plt.show()

print(type(df_raw))
print(type(df_raw["AF7"]) if isinstance(df_raw, pd.DataFrame) else "df_raw is not a DataFrame")



df_raw.columns

f, pxx_raw = welch(df_raw.loc[:, "AF7"].to_numpy(), fs=fs, nperseg=fs)
f, pxx_filt = welch(df_filt.loc[:, "AF7"].to_numpy(), fs=fs, nperseg=fs)


plt.figure(figsize=(8,5))
plt.semilogy(f, pxx_raw, label="Raw")
plt.semilogy(f, pxx_filt, label="Filtered")
plt.axvline(30, color="gray", linestyle="--", label="30 Hz cutoff")
plt.xlim(0, 80)
plt.xlabel("Frequency (Hz)")
plt.ylabel("Power")
plt.title("AF7 — Power Spectral Density")
plt.legend()
plt.show()



"""
> Add blockquote

"""



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -----------------------------
# 1. Flat line & spike detection
# -----------------------------
def detect_flat_and_spikes(df, channels, window_size=256, flat_var_thresh=1e-6, spike_std_factor=4):
    flat_dict = {}
    spike_dict = {}

    for ch in channels:
        signal = df[ch].values

        # --- Flat line detection ---
        flat_indices = []
        for i in range(len(signal) - window_size):
            window = signal[i:i+window_size]
            if np.var(window) < flat_var_thresh:
                flat_indices.append(i)
        flat_dict[ch] = flat_indices

        # --- Spike detection ---
        mean = np.mean(signal)
        std = np.std(signal)
        spike_indices = np.where(np.abs(signal - mean) > spike_std_factor * std)[0]
        spike_dict[ch] = spike_indices

    return flat_dict, spike_dict

# -----------------------------
# 2. High-frequency detection
# -----------------------------
def detect_high_frequency_channels(eeg_data, fs=256, hf_freq=30, hf_ratio=0.3, window_sec=0.5, channels=None):
    if channels is None:
        channels = [f'ch{i}' for i in range(eeg_data.shape[1])]

    n_channels = eeg_data.shape[1]
    hf_dict = {}

    for i in range(n_channels):
        sig = eeg_data[:, i]
        window_size = int(fs * window_sec)
        hf_indices = []

        for start in range(0, len(sig) - window_size, window_size):
            window = sig[start:start+window_size]
            fft_vals = np.abs(np.fft.rfft(window))
            freqs = np.fft.rfftfreq(len(window), d=1/fs)

            total_power = np.sum(fft_vals)
            hf_power = np.sum(fft_vals[freqs > hf_freq])
            if total_power > 0 and (hf_power / total_power) > hf_ratio:
                hf_indices.extend(range(start, start + window_size))

        hf_dict[channels[i]] = np.array(hf_indices)

    return hf_dict

# -----------------------------
# 3. High-variance detection
# -----------------------------
def detect_high_variance_channels(eeg_data, fs=256, var_threshold=100, window_sec=0.5, channels=None):
    if channels is None:
        channels = [f'ch{i}' for i in range(eeg_data.shape[1])]

    n_channels = eeg_data.shape[1]
    hv_dict = {}

    for i in range(n_channels):
        sig = eeg_data[:, i]
        window_size = int(fs * window_sec)
        hv_indices = []

        for start in range(0, len(sig) - window_size, window_size):
            window = sig[start:start+window_size]
            if np.var(window) > var_threshold:
                hv_indices.extend(range(start, start + window_size))

        hv_dict[channels[i]] = np.array(hv_indices)

    return hv_dict

# -----------------------------
# 4. Plotting function
# -----------------------------
def plot_eeg_with_all_artifacts(df, channels, flat_dict, spike_dict, hf_dict, hv_dict):
    n_channels = len(channels)
    fig, axes = plt.subplots(n_channels, 1, figsize=(16, 3*n_channels), sharex=True)

    if n_channels == 1:
        axes = [axes]

    for i, ch in enumerate(channels):
        ax = axes[i]
        signal = df[ch].values
        t = df['lsl_timestamp'].values

        ax.plot(t, signal, color='blue', label='EEG signal')

        # Flat lines (red)
        flat_idx = flat_dict[ch]
        if len(flat_idx) > 0:
            ax.scatter(t[flat_idx], signal[flat_idx], color='red', s=10, label='Flat line')

        # Spikes (green)
        spike_idx = spike_dict[ch]
        if len(spike_idx) > 0:
            ax.scatter(t[spike_idx], signal[spike_idx], color='green', s=10, label='Spikes')

        # High-frequency (orange)
        hf_idx = hf_dict[ch]
        if len(hf_idx) > 0:
            ax.scatter(t[hf_idx], signal[hf_idx], color='orange', s=5, label='High-Freq')

        # High-variance (purple)
        hv_idx = hv_dict[ch]
        if len(hv_idx) > 0:
            ax.scatter(t[hv_idx], signal[hv_idx], color='yellow', s=5, label='High-Variance')

        ax.set_ylabel(f'{ch} (μV)')
        ax.legend(loc='upper right')
        ax.grid(True)

    axes[-1].set_xlabel('Time (s)')
    plt.suptitle('EEG Channels with Flat Lines (red), Spikes (green), High-Frequency (orange), High-Variance (purple)', fontsize=16)
    plt.tight_layout(rect=[0,0,1,0.95])
    plt.show()

# -----------------------------
# 5. Example usage
# -----------------------------
channels = ['TP9','AF7','AF8','TP10']

# Detect flat lines and spikes
flats, spikes = detect_flat_and_spikes(df, channels, window_size=256, flat_var_thresh=1e-6, spike_std_factor=4)

# Convert df to numpy array for high-frequency and high-variance detection
eeg_array = df[channels].values
hf_result = detect_high_frequency_channels(eeg_array, fs=256, hf_freq=30, hf_ratio=0.3, window_sec=0.5, channels=channels)
hv_result = detect_high_variance_channels(eeg_array, fs=256, var_threshold=200, window_sec=0.1, channels=channels)

# Plot combined artifacts
plot_eeg_with_all_artifacts(df, channels, flats, spikes, hf_result, hv_result)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -----------------------------
# 1. Flat line & spike detection (adaptive thresholds)
# -----------------------------
def detect_flat_and_spikes(df, channels, window_size=256, flat_var_factor=0.01, spike_std_factor=4):
    """
    Detects flat lines and spikes in EEG channels.
    - flat_var_factor: fraction of channel variance to define flat lines
    - spike_std_factor: multiplier of std to detect spikes
    """
    flat_dict = {}
    spike_dict = {}

    for ch in channels:
        signal = df[ch].values
        channel_var = np.var(signal)
        flat_var_thresh = flat_var_factor * channel_var  # adaptive per channel

        # --- Flat line detection ---
        flat_indices = []
        for i in range(len(signal) - window_size):
            window = signal[i:i+window_size]
            if np.var(window) < flat_var_thresh:
                flat_indices.append(i)
        flat_dict[ch] = flat_indices

        # --- Spike detection ---
        mean = np.mean(signal)
        std = np.std(signal)
        spike_indices = np.where(np.abs(signal - mean) > spike_std_factor * std)[0]
        spike_dict[ch] = spike_indices

    return flat_dict, spike_dict

# -----------------------------
# 2. High-frequency detection
# -----------------------------
def detect_high_frequency_channels(eeg_data, fs=256, hf_freq=30, hf_ratio=0.3, window_sec=0.5, channels=None):
    if channels is None:
        channels = [f'ch{i}' for i in range(eeg_data.shape[1])]

    n_channels = eeg_data.shape[1]
    hf_dict = {}

    for i in range(n_channels):
        sig = eeg_data[:, i]
        window_size = int(fs * window_sec)
        hf_indices = []

        for start in range(0, len(sig) - window_size, window_size):
            window = sig[start:start+window_size]
            fft_vals = np.abs(np.fft.rfft(window))
            freqs = np.fft.rfftfreq(len(window), d=1/fs)

            total_power = np.sum(fft_vals)
            hf_power = np.sum(fft_vals[freqs > hf_freq])
            if total_power > 0 and (hf_power / total_power) > hf_ratio:
                hf_indices.extend(range(start, start + window_size))

        hf_dict[channels[i]] = np.array(hf_indices)

    return hf_dict

# -----------------------------
# 3. High-variance detection (adaptive thresholds)
# -----------------------------
def detect_high_variance_channels(eeg_data, fs=256, var_factor=2.0, window_sec=0.5, channels=None):
    """
    Detects windows of high variance.
    - var_factor: multiplier of channel mean variance to detect high variance
    """
    if channels is None:
        channels = [f'ch{i}' for i in range(eeg_data.shape[1])]

    n_channels = eeg_data.shape[1]
    hv_dict = {}

    for i in range(n_channels):
        sig = eeg_data[:, i]
        channel_var = np.var(sig)
        var_threshold = var_factor * channel_var  # adaptive per channel
        window_size = int(fs * window_sec)
        hv_indices = []

        for start in range(0, len(sig) - window_size, window_size):
            window = sig[start:start+window_size]
            if np.var(window) > var_threshold:
                hv_indices.extend(range(start, start + window_size))

        hv_dict[channels[i]] = np.array(hv_indices)

    return hv_dict

# -----------------------------
# 4. Plotting function
# -----------------------------
def plot_eeg_with_all_artifacts(df, channels, flat_dict, spike_dict, hf_dict, hv_dict):
    n_channels = len(channels)
    fig, axes = plt.subplots(n_channels, 1, figsize=(16, 3*n_channels), sharex=True)

    if n_channels == 1:
        axes = [axes]

    for i, ch in enumerate(channels):
        ax = axes[i]
        signal = df[ch].values
        t = df['lsl_timestamp'].values

        ax.plot(t, signal, color='blue', label='EEG signal')

        # Flat lines (red)
        flat_idx = flat_dict[ch]
        if len(flat_idx) > 0:
            ax.scatter(t[flat_idx], signal[flat_idx], color='red', s=10, label='Flat line')

        # Spikes (green)
        spike_idx = spike_dict[ch]
        if len(spike_idx) > 0:
            ax.scatter(t[spike_idx], signal[spike_idx], color='green', s=10, label='Spikes')

        # High-frequency (orange)
        hf_idx = hf_dict[ch]
        if len(hf_idx) > 0:
            ax.scatter(t[hf_idx], signal[hf_idx], color='orange', s=5, label='High-Freq')

        # High-variance (purple)
        hv_idx = hv_dict[ch]
        if len(hv_idx) > 0:
            ax.scatter(t[hv_idx], signal[hv_idx], color='yellow', s=5, label='High-Variance')

        ax.set_ylabel(f'{ch} (μV)')
        ax.legend(loc='upper right')
        ax.grid(True)

    axes[-1].set_xlabel('Time (s)')
    plt.suptitle('EEG Channels with Flat Lines (red), Spikes (green), High-Frequency (orange), High-Variance (purple)', fontsize=16)
    plt.tight_layout(rect=[0,0,1,0.95])
    plt.show()

# -----------------------------
# 5. Example usage
# -----------------------------
channels = ['TP9','AF7','AF8','TP10']

# Detect flat lines and spikes
flats, spikes = detect_flat_and_spikes(df, channels, window_size=256, flat_var_factor=0.01, spike_std_factor=4)

# Convert df to numpy array for high-frequency and high-variance detection
eeg_array = df[channels].values
hf_result = detect_high_frequency_channels(eeg_array, fs=256, hf_freq=50, hf_ratio=0.3, window_sec=0.5, channels=channels)
hv_result = detect_high_variance_channels(eeg_array, fs=256, var_factor=2.0, window_sec=0.1, channels=channels)

# Plot combined artifacts
plot_eeg_with_all_artifacts(df, channels, flats, spikes, hf_result, hv_result)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt, iirnotch

# -----------------------------
# 1. Bandpass filter
# -----------------------------
def bandpass_filter(signal, lowcut=1, highcut=45, fs=256, order=4):
    nyq = 0.5 * fs
    b, a = butter(order, [lowcut/nyq, highcut/nyq], btype='band')
    return filtfilt(b, a, signal)

# -----------------------------
# 2. Notch filter
# -----------------------------
def notch_filter(signal, freq=50, fs=256, Q=30):
    b, a = iirnotch(freq/(fs/2), Q)
    return filtfilt(b, a, signal)

# -----------------------------
# 3. Apply filters to multiple channels
# -----------------------------
def apply_filters(df, channels, fs=256, lowcut=1, highcut=45, notch_freq=50):
    df_filtered = df.copy()
    for ch in channels:
        sig = df[ch].values
        sig_bp = bandpass_filter(sig, lowcut=lowcut, highcut=highcut, fs=fs)
        sig_filt = notch_filter(sig_bp, freq=notch_freq, fs=fs)
        df_filtered[ch] = sig_filt
    return df_filtered

# -----------------------------
# 4. Plot filtered vs raw
# -----------------------------
def plot_all_channels_filtered_vs_raw(df_raw, df_filtered, channels, start=0, end=1024):
    """
    Plots raw vs filtered EEG signals for multiple channels in subplots.
    """
    n_channels = len(channels)
    fig, axes = plt.subplots(n_channels, 1, figsize=(15, 3*n_channels), sharex=True)

    if n_channels == 1:
        axes = [axes]

    for i, ch in enumerate(channels):
        t = df_raw['lsl_timestamp'].values[start:end]
        raw_sig = df_raw[ch].values[start:end]
        filt_sig = df_filtered[ch].values[start:end]

        ax = axes[i]
        ax.plot(t, raw_sig, label='Raw/Noisy', color='red', alpha=0.6)
        ax.plot(t, filt_sig, label='Filtered', color='blue')
        ax.set_ylabel(f'{ch} (μV)')
        ax.grid(True)
        ax.legend(loc='upper right')

    axes[-1].set_xlabel('Time (s)')
    plt.suptitle('Raw vs Filtered EEG Signals', fontsize=16)
    plt.tight_layout(rect=[0,0,1,0.95])
    plt.show()


# -----------------------------
# 5. Example usage
# -----------------------------
channels = ['TP9','AF7','AF8','TP10']

# Apply filters
df_filtered = apply_filters(df, channels, fs=256, lowcut=1, highcut=45, notch_freq=50)

# Compare filtered vs raw for one channel
plot_all_channels_filtered_vs_raw(df, df_filtered, channels, start=0, end=1024)

import numpy as np
import matplotlib.pyplot as plt

def plot_filtered_vs_raw_with_artifacts(df_raw, df_filtered, channels, flat_dict, spike_dict, hf_dict, hv_dict, start=0, end=1024):
    """
    Plots raw vs filtered EEG signals for multiple channels with artifact markers.
    """
    n_channels = len(channels)
    fig, axes = plt.subplots(n_channels, 1, figsize=(16, 3*n_channels), sharex=True)

    if n_channels == 1:
        axes = [axes]

    for i, ch in enumerate(channels):
        t = df_raw['lsl_timestamp'].values[start:end]
        raw_sig = df_raw[ch].values[start:end]
        filt_sig = df_filtered[ch].values[start:end]

        ax = axes[i]

        # Raw vs filtered
        ax.plot(t, raw_sig, label='Raw/Noisy', color='red', alpha=0.6)
        ax.plot(t, filt_sig, label='Filtered', color='blue')

        # --- Overlay artifact markers on filtered signal ---
        # Flat lines (red dots)
        flat_idx = np.array(flat_dict[ch])
        flat_idx = flat_idx[(flat_idx >= start) & (flat_idx < end)]
        if len(flat_idx) > 0:
            ax.scatter(t[flat_idx-start], filt_sig[flat_idx-start], color='red', s=15, label='Flat line')

        # Spikes (green dots)
        spike_idx = np.array(spike_dict[ch])
        spike_idx = spike_idx[(spike_idx >= start) & (spike_idx < end)]
        if len(spike_idx) > 0:
            ax.scatter(t[spike_idx-start], filt_sig[spike_idx-start], color='green', s=15, label='Spikes')

        # High-frequency (orange dots)
        hf_idx = np.array(hf_dict[ch])
        hf_idx = hf_idx[(hf_idx >= start) & (hf_idx < end)]
        if len(hf_idx) > 0:
            ax.scatter(t[hf_idx-start], filt_sig[hf_idx-start], color='orange', s=5, label='High-Freq')

        # High-variance (purple dots)
        hv_idx = np.array(hv_dict[ch])
        hv_idx = hv_idx[(hv_idx >= start) & (hv_idx < end)]
        if len(hv_idx) > 0:
            ax.scatter(t[hv_idx-start], filt_sig[hv_idx-start], color='purple', s=5, label='High-Variance')

        ax.set_ylabel(f'{ch} (μV)')
        ax.grid(True)
        ax.legend(loc='upper right')

    axes[-1].set_xlabel('Time (s)')
    plt.suptitle('Raw vs Filtered EEG with Artifact Markers', fontsize=16)
    plt.tight_layout(rect=[0,0,1,0.95])
    plt.show()

channels = ['TP9','AF7','AF8','TP10']

# 1. Apply filters
df_filtered = apply_filters(df, channels, fs=256, lowcut=1, highcut=45, notch_freq=50)

# 2. Detect artifacts (adaptive thresholds)
flats, spikes = detect_flat_and_spikes(df, channels, window_size=256, flat_var_factor=0.01, spike_std_factor=4)
eeg_array = df[channels].values
hf_result = detect_high_frequency_channels(eeg_array, fs=256, hf_freq=30, hf_ratio=0.3, window_sec=0.5, channels=channels)
hv_result = detect_high_variance_channels(eeg_array, fs=256, var_factor=2.0, window_sec=0.1, channels=channels)

# 3. Plot raw vs filtered with artifact markers
plot_filtered_vs_raw_with_artifacts(df, df_filtered, channels, flats, spikes, hf_result, hv_result, start=0, end=1024)



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt, iirnotch

# -----------------------------
# 1. Artifact detection: flat lines & spikes
# -----------------------------
def detect_flat_and_spikes(df, channels, window_size=256, flat_var_factor=0.01, spike_std_factor=4):
    """
    Detects flat lines and spikes in EEG channels (adaptive thresholds).
    """
    flat_dict = {}
    spike_dict = {}

    for ch in channels:
        signal = df[ch].values
        channel_var = np.var(signal)
        flat_var_thresh = flat_var_factor * channel_var  # adaptive per channel

        # --- Flat line detection ---
        flat_indices = []
        for i in range(len(signal) - window_size):
            window = signal[i:i+window_size]
            if np.var(window) < flat_var_thresh:
                flat_indices.append(i)
        flat_dict[ch] = flat_indices

        # --- Spike detection ---
        mean = np.mean(signal)
        std = np.std(signal)
        spike_indices = np.where(np.abs(signal - mean) > spike_std_factor * std)[0]
        spike_dict[ch] = spike_indices

    return flat_dict, spike_dict

# -----------------------------
# 2. High-frequency detection
# -----------------------------
def detect_high_frequency_channels(eeg_data, fs=256, hf_freq=30, hf_ratio=0.3, window_sec=0.5, channels=None):
    if channels is None:
        channels = [f'ch{i}' for i in range(eeg_data.shape[1])]

    n_channels = eeg_data.shape[1]
    hf_dict = {}

    for i in range(n_channels):
        sig = eeg_data[:, i]
        window_size = int(fs * window_sec)
        hf_indices = []

        for start in range(0, len(sig) - window_size, window_size):
            window = sig[start:start+window_size]
            fft_vals = np.abs(np.fft.rfft(window))
            freqs = np.fft.rfftfreq(len(window), d=1/fs)

            total_power = np.sum(fft_vals)
            hf_power = np.sum(fft_vals[freqs > hf_freq])
            if total_power > 0 and (hf_power / total_power) > hf_ratio:
                hf_indices.extend(range(start, start + window_size))

        hf_dict[channels[i]] = np.array(hf_indices)

    return hf_dict

# -----------------------------
# 3. High-variance detection
# -----------------------------
def detect_high_variance_channels(eeg_data, fs=256, var_factor=2.0, window_sec=0.5, channels=None):
    if channels is None:
        channels = [f'ch{i}' for i in range(eeg_data.shape[1])]

    n_channels = eeg_data.shape[1]
    hv_dict = {}

    for i in range(n_channels):
        sig = eeg_data[:, i]
        channel_var = np.var(sig)
        var_threshold = var_factor * channel_var  # adaptive per channel
        window_size = int(fs * window_sec)
        hv_indices = []

        for start in range(0, len(sig) - window_size, window_size):
            window = sig[start:start+window_size]
            if np.var(window) > var_threshold:
                hv_indices.extend(range(start, start + window_size))

        hv_dict[channels[i]] = np.array(hv_indices)

    return hv_dict

# -----------------------------
# 4. Filters: bandpass and notch
# -----------------------------
def bandpass_filter(signal, lowcut=1, highcut=45, fs=256, order=4):
    nyq = 0.5 * fs
    b, a = butter(order, [lowcut/nyq, highcut/nyq], btype='band')
    return filtfilt(b, a, signal)

def notch_filter(signal, freq=50, fs=256, Q=30):
    b, a = iirnotch(freq/(fs/2), Q)
    return filtfilt(b, a, signal)

def apply_filters(df, channels, fs=256, lowcut=1, highcut=45, notch_freq=50):
    df_filtered = df.copy()
    for ch in channels:
        sig = df[ch].values
        sig_bp = bandpass_filter(sig, lowcut=lowcut, highcut=highcut, fs=fs)
        sig_filt = notch_filter(sig_bp, freq=notch_freq, fs=fs)
        df_filtered[ch] = sig_filt
    return df_filtered

# -----------------------------
# 5. Plot raw vs filtered with artifacts
# -----------------------------
def plot_filtered_vs_raw_with_artifacts(df_raw, df_filtered, channels, flat_dict, spike_dict, hf_dict, hv_dict, start=0, end=1024):
    n_channels = len(channels)
    fig, axes = plt.subplots(n_channels, 1, figsize=(16, 3*n_channels), sharex=True)

    if n_channels == 1:
        axes = [axes]

    for i, ch in enumerate(channels):
        t = df_raw['lsl_timestamp'].values[start:end]
        raw_sig = df_raw[ch].values[start:end]
        filt_sig = df_filtered[ch].values[start:end]

        ax = axes[i]

        # Raw vs filtered
        ax.plot(t, raw_sig, label='Raw/Noisy', color='red', alpha=0.6)
        ax.plot(t, filt_sig, label='Filtered', color='blue')

        # --- Overlay artifact markers on filtered signal ---
        for idx, color, label in zip([flat_dict[ch], spike_dict[ch], hf_dict[ch], hv_dict[ch]],
                                     ['red','green','orange','purple'],
                                     ['Flat line','Spikes','High-Freq','High-Variance']):
            idx = np.array(idx)
            idx = idx[(idx >= start) & (idx < end)]
            if len(idx) > 0:
                ax.scatter(t[idx-start], filt_sig[idx-start], color=color, s=10, label=label)

        ax.set_ylabel(f'{ch} (μV)')
        ax.grid(True)
        ax.legend(loc='upper right')

    axes[-1].set_xlabel('Time (s)')
    plt.suptitle('Raw vs Filtered EEG with Artifact Markers', fontsize=16)
    plt.tight_layout(rect=[0,0,1,0.95])
    plt.show()



# -----------------------------
# 4. Plotting function
# -----------------------------
def plot_eeg_with_all_artifacts(df, channels, flat_dict, spike_dict, hf_dict, hv_dict):
    n_channels = len(channels)
    fig, axes = plt.subplots(n_channels, 1, figsize=(16, 3*n_channels), sharex=True)

    if n_channels == 1:
        axes = [axes]

    for i, ch in enumerate(channels):
        ax = axes[i]
        signal = df[ch].values
        t = df['lsl_timestamp'].values

        ax.plot(t, signal, color='blue', label='EEG signal')

        # Flat lines (red)
        flat_idx = flat_dict[ch]
        if len(flat_idx) > 0:
            ax.scatter(t[flat_idx], signal[flat_idx], color='red', s=10, label='Flat line')

        # Spikes (green)
        spike_idx = spike_dict[ch]
        if len(spike_idx) > 0:
            ax.scatter(t[spike_idx], signal[spike_idx], color='green', s=10, label='Spikes')

        # High-frequency (orange)
        hf_idx = hf_dict[ch]
        if len(hf_idx) > 0:
            ax.scatter(t[hf_idx], signal[hf_idx], color='orange', s=5, label='High-Freq')

        # High-variance (purple)
        hv_idx = hv_dict[ch]
        if len(hv_idx) > 0:
            ax.scatter(t[hv_idx], signal[hv_idx], color='yellow', s=5, label='High-Variance')

        ax.set_ylabel(f'{ch} (μV)')
        ax.legend(loc='upper right')
        ax.grid(True)

    axes[-1].set_xlabel('Time (s)')
    plt.suptitle('EEG Channels with Flat Lines (red), Spikes (green), High-Frequency (orange), High-Variance (purple)', fontsize=16)
    plt.tight_layout(rect=[0,0,1,0.95])
    plt.show()

# -----------------------------
# 6. Example usage
# -----------------------------
channels = ['TP9','AF7','AF8','TP10']

# Detect artifacts
flats, spikes = detect_flat_and_spikes(df, channels, window_size=256, flat_var_factor=0.01, spike_std_factor=4)
eeg_array = df[channels].values
hf_result = detect_high_frequency_channels(eeg_array, fs=256, hf_freq=30, hf_ratio=0.3, window_sec=0.5, channels=channels)
hv_result = detect_high_variance_channels(eeg_array, fs=256, var_factor=2.0, window_sec=0.1, channels=channels)

# Apply filters
df_filtered = apply_filters(df, channels, fs=256, lowcut=1, highcut=45, notch_freq=50)

plot_eeg_with_all_artifacts(df, channels, flats, spikes, hf_result, hv_result)

# Plot raw vs filtered with artifact markers
plot_filtered_vs_raw_with_artifacts(df, df_filtered, channels, flats, spikes, hf_result, hv_result, start=0, end=1024)

