# Generated by Django 4.2.29 on 2026-03-31 04:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_otp',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('academic_level', models.CharField(max_length=100)),
                ('alert_time', models.CharField(max_length=100)),
                ('sleep_hours', models.FloatField()),
                ('sleep_quality', models.CharField(max_length=100)),
                ('consumes_caffeine', models.BooleanField(default=False)),
                ('caffeine_types', models.TextField(blank=True, help_text='Comma separated list')),
                ('caffeine_servings', models.IntegerField(default=0)),
                ('caffeine_timing', models.CharField(blank=True, max_length=100)),
                ('learning_style', models.CharField(max_length=100)),
                ('study_subjects', models.TextField(blank=True)),
                ('session_length', models.CharField(max_length=100)),
                ('takes_breaks', models.CharField(max_length=100)),
                ('study_time_of_day', models.CharField(max_length=100)),
                ('procrastination_level', models.IntegerField()),
                ('study_location', models.TextField(blank=True)),
                ('sound_environment', models.CharField(max_length=100)),
                ('lighting_preference', models.CharField(max_length=100)),
                ('phone_location', models.CharField(max_length=100)),
                ('distractions', models.TextField(blank=True)),
                ('exercise_frequency', models.CharField(max_length=100)),
                ('eating_timing', models.CharField(max_length=100)),
                ('health_conditions', models.TextField(blank=True)),
                ('main_goals', models.TextField(blank=True)),
                ('study_effectiveness', models.IntegerField()),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('inference_id', models.CharField(max_length=100)),
                ('recommendation_category', models.CharField(max_length=50)),
                ('stimulus_name', models.CharField(max_length=100)),
                ('trigger_reason', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('action_started_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondBrain_App.userprofile')),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
    ]
