# Generated by Django 4.2.29 on 2026-04-04 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0002_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('csv_file_path', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_duration_seconds', models.FloatField()),
                ('average_focus_score', models.FloatField()),
                ('peak_focus_score', models.FloatField()),
                ('relaxed_seconds', models.FloatField()),
                ('neutral_seconds', models.FloatField()),
                ('concentrating_seconds', models.FloatField()),
                ('data_points_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondBrain_App.userprofile')),
            ],
            options={
                'db_table': 'session_summary',
            },
        ),
    ]
