# Generated by Django 4.2.29 on 2026-04-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0003_sessionsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
