# Generated by Django 4.2.29 on 2026-04-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0004_userprofile_onboarding_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='onboarding_complete',
        ),
    ]
