# Generated by Django 4.2.29 on 2026-04-14 02:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0006_sessionsummary_avg_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSummary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='secondBrain_App.userprofile')),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_focus_time_minutes', models.FloatField(default=0)),
                ('average_focus_score', models.FloatField(default=0)),
                ('best_focus_score', models.FloatField(default=0)),
                ('optimal_focus_time_of_day', models.CharField(blank=True, max_length=20)),
                ('first_session_date', models.DateField(blank=True, null=True)),
                ('last_session_date', models.DateField(blank=True, null=True)),
                ('stimulus_used', models.CharField(blank=True, max_length=200)),
                ('recommendation_feedback', models.CharField(blank=True, max_length=50)),
                ('most_effective_stimulus', models.CharField(blank=True, max_length=50)),
                ('least_effective_stimulus', models.CharField(blank=True, max_length=50)),
                ('average_feedback_rating', models.IntegerField(default=0)),
                ('positive_feedback_count', models.IntegerField(default=0)),
                ('negative_feedback_count', models.IntegerField(default=0)),
                ('overall_sentiment_score', models.FloatField(default=0)),
                ('total_recommendations_rated', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_summary',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('feedback_type', models.CharField(blank=True, max_length=50)),
                ('trigger', models.CharField(blank=True, max_length=100)),
                ('helpfulness_rating', models.IntegerField(blank=True, null=True)),
                ('ease_of_use_rating', models.IntegerField(blank=True, null=True)),
                ('recommendation_relevance', models.IntegerField(blank=True, null=True)),
                ('overall_rating', models.IntegerField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secondBrain_App.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondBrain_App.userprofile')),
            ],
            options={
                'db_table': 'user_feedback',
            },
        ),
    ]
