# Generated by Django 4.2.30 on 2026-04-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0008_recommendation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsummary',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
