# Generated by Django 4.2.30 on 2026-04-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0010_recommendation_session_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='session_id',
        ),
    ]
