# Generated by Django 4.2.30 on 2026-04-25 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0012_presessioncheckin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presessioncheckin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondBrain_App.userprofile'),
        ),
    ]
