# Generated by Django 4.2.30 on 2026-04-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0013_alter_presessioncheckin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presessioncheckin',
            name='current_location',
            field=models.CharField(blank=True, help_text='Current study location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presessioncheckin',
            name='current_noise',
            field=models.CharField(blank=True, help_text='Current noise level/description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presessioncheckin',
            name='lighting_conditions',
            field=models.CharField(blank=True, help_text='Lighting conditions', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presessioncheckin',
            name='study_method',
            field=models.CharField(blank=True, help_text='Study method/approach', max_length=100, null=True),
        ),
    ]
