# Generated by Django 4.2.30 on 2026-04-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0014_alter_presessioncheckin_current_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersummary',
            name='user',
        ),
        migrations.AddField(
            model_name='presessioncheckin',
            name='session_name',
            field=models.CharField(blank=True, help_text='User-provided session name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.DeleteModel(
            name='UserSummary',
        ),
    ]
