# Generated by Django 4.2.30 on 2026-04-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0015_remove_usersummary_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsummary',
            name='alpha_avg',
            field=models.FloatField(default=0.0, help_text='Average Alpha wave power (Hz)'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='beta_avg',
            field=models.FloatField(default=0.0, help_text='Average Beta wave power (Hz)'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='focus_depth',
            field=models.CharField(default='Unknown', help_text='Focus depth: Deep Flow, Light Focus, Surface Level', max_length=50),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='gamma_avg',
            field=models.FloatField(default=0.0, help_text='Average Gamma wave power (Hz)'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='neural_state',
            field=models.CharField(default='Unknown', help_text='Neural state: Focus, Drowsy, Anxious, Distracted, Neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='signal_integrity',
            field=models.CharField(default='Unknown', help_text='Signal integrity: Clean, Artifact-Heavy, Poor', max_length=50),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='theta_avg',
            field=models.FloatField(default=0.0, help_text='Average Theta wave power (Hz)'),
        ),
    ]
