# Generated by Django 4.2.30 on 2026-05-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0016_sessionsummary_alpha_avg_sessionsummary_beta_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='optimal_study_environment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='personalized_recommendation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_study_methods',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='what_to_avoid',
            field=models.TextField(blank=True, default=''),
        ),
    ]
