# Generated by Django 4.2.29 on 2026-05-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0017_recommendation_optimal_study_environment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='optimal_study_environment',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='personalized_recommendation',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_study_methods',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='what_to_avoid',
        ),
    ]
