# Generated by Django 4.2.29 on 2026-05-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondBrain_App', '0018_remove_recommendation_optimal_study_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='optimal_study_environment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='personalized_recommendation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_study_methods',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='what_to_avoid',
            field=models.TextField(blank=True, default=''),
        ),
    ]
